swagger: '2.0'
info:
  description: This server provides schedule creating functionality for UBC.
  version: 0.0.1
  title: UBC Course Schedule Creator
host: schedulecreator.herokuapp.com
schemes:
  - http
  - https

paths:
  /schedules:
    get:
      summary: GET /schedules
      description: 'Returns UBC course schedules given input courses.'
      produces:
        - application/json
      parameters:
        - in: query
          name: courses
          description: Course names to create a schedule with.
          required: true
          type: array
          items:
            type: string
          example: ['MATH 100', 'CPSC 221']
        - in: query
          name: term
          description: The term to create the schedules for.
          schema:
            type: string
            enum: [1, 2, 1-2]
            example: 2
          default: 1-2
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/SchedulesResponse'
        400:
          description: Missing required parameters.

  /autocomplete:
    get:
      summary: GET /autocomplete
      description: 'Returns autocompleted valid courses.'
      produces:
        - application/json
      parameters:
        - in: query
          name: text
          description: Text to autocomplete.
          required: true
          type: string
      responses:
        200:
          description: An array of valid courses.
          schema:
            $ref: '#/definitions/AutocompleteResponse'
        400:
          description: Missing required parameters.

definitions:
  SchedulesResponse:
    properties:
      OK:
        type: boolean
        example: true
      status:
        type: int
        example: 200
      body:
        type: array
        items:
          $ref: '#/definitions/Schedule'

  AutocompleteResponse:
    properties:
      OK:
        type: boolean
        example: true
      status:
        type: int
        example: 200
      body:
        type: array
        items:
          type: string
        example: ['MATH 001', 'MATH 002', 'MATH 100', 'MATH 101']

  Schedule:
    properties:
      courses:
        type: array
        items:
          $ref: '#/definitions/Course'

  Course:
    properties:
      name:
        type: string
        example: MATH 100 102
      sessions:
        type: array
        items:
          $ref: '#/definitions/Session'

  Session:
    properties:
      activity:
        type: string
        example: Lecture
      term:
        type: string
        example: 1
      day:
        type: string
        example: Thu
      start:
        type: int
        example: 800
      end:
        type: int
        example: 930
